language: c++
before_install:
  - sudo apt-get install -qy build-essential cmake git libx11-dev libx11-xcb-dev freeglut3-dev libxcb-image0-dev libudev-dev libjpeg8-dev libopenal-dev libsndfile1-dev libfreetype6-dev libxcb-randr0-dev
  - |
    curl -L "https://github.com/SFML/SFML/archive/2.4.0.tar.gz" | tar -xz
    cd SFML*
    cmake . && make
    sudo make install
    cd ..
addons:
    apt:
      sources:
        - george-edison55-precise-backports
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - gfortran-6
        - g++-6
        - binutils
        - cmake-data
        - cmake
script:
    - mkdir -p bin
    - cd bin
    - cmake ..
    - make

