language: c++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
        packages:
            - g++-6
            - cmake
            - cmake-data
            - libsfml-dev

script:
    - mkdir -p bin
    - cd bin
    - cmake ..
    - make
